name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Configure Credentials
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.DEPLOYMENT_TOKEN }}

      # Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository }}:latest .

      # Push the Docker image to GHCR
      - name: Push Docker image to GHCR
        run: |
          docker push ghcr.io/${{ github.repository }}:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      # Deploy to on-premises server
      - name: Deploy to on-premises host
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          script: |
            sh -c '
            docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.DEPLOYMENT_TOKEN }}
            docker pull ghcr.io/${{ github.repository }}:latest

            # Stop and remove any running container
            docker stop caupolican || true
            docker rm caupolican || true

            # Create directories
            mkdir -p /tmp/caupolican/out

            # Run the container
            docker run -d --name caupolican \
            --env-file /tmp/caupolican/router.env \
            -v /tmp/caupolican/out:/out \
            -p 80:8080 \
            --ulimit nofile=65536:65536 \
            --restart=always \
            ghcr.io/${{ github.repository }}:latest
            '
